name: AFKScoreboard
version: '${version}'
main: space.gorogoro.afkscoreboard.AFKScoreboard
api-version: '1.21.11'
description: This plugin works with AxAFKZone to display a ranking scoreboard based on AFK time.
author: kubotan
website: https://www.gorogoro.space/

permissions:
  afkscoreboard.debug:
    description: 見た目ボーナスを待たずに付与する
    default: op

dependencies:
  server:
    AxAFKZone:
      load: BEFORE
      required: true
      join-classpath: true

