name: AFKScoreboard
version: '${version}'
softdepend: [AxAFKZone]
main: me.dragonwhale7.afkscoreboard.AFKScoreboard
api-version: '1.21.11'
description: This plugin works with AxAFKZone to display a ranking scoreboard based on AFK time.
author: abcdmoon
website: https://www.gorogoro.space/

